![image](https://github.com/user-attachments/assets/3d34203a-8fa4-49c4-a57b-0c5e57818bda)

```
실행 예시 ```
전송할 문자: hello
http://example.com 서버 연결 성공
http://example.com 서버에 데이터 전송: hello
http://example.com 서버 연결 해제
```

```java
package exception.ex0;

public class NetworkServiceV0{

		public void sendMessage(String data){
		
				String address = "http://example.com";
				NetworkClientV0 client = new NetworkClientV0(address);
				
				client.connect();
				client.send(data);
				client.disconnect();
		}
}
```

```java
public class MainV0{

		public static void main(STring[] args){
		
				NetworkService0 networkService = new NetworkServiceV0();
				
				Scanner scanner = new Scanner(System.in);
				
				while(true){
						System.out.print("전송할 문자: ");
						String input = scanner.nextLine();
						if(input.equals("exit")){
								break;
						}
						
						networkService.sendMessage(input);
						System.out.println();
				}
				
				System.out.println("프로그램을 정상 종료합니다.");
		}
}
```
<br>

~예외 처리가 왜 필요한지 

외부 서버와 통신할 때 다양한 문제들일 발생

- 외부 서버와 연결에 실패한다 (네트워크 오류 등등)
- 데이터 전송에 문제가 발생한다

`서버 연결 실패` : send 호출이 안됨

`서버에 데이터 전송 실패`

연결에 실패하면 데이터를 전송하지 않아야 하는데, 여기서는 데이터를 전송한다.

오류 로그를 남겨야 한다.

```
자바의 경우 GC가 있기 때문에 JVM 메모리에 있는 인스턴스는 자동으로 해제할 수 있다.
하지만 외부 연결과 같은 자바 외부의 자원은 자동으로 해제가 되지 않는다.
따라서 외부 자원을 사용한 후에는 연결을 해제해서 외부 자원을 반드시! 반납해야 한다.

~ 연결에 성공하고 메시지 전송이 실패한 경우에 연결을 안 끊어서 문제 발생
~ 반납하도록 해보자
```

```java
package exception.ex1;

public class NetworkServiceV1_1 {
	 
	 public void sendMessage(String data) {
		 
		 String address = "http://example.com";
		 NetworkClientV1 client = new NetworkClientV1(address);
		 
		 client.initError(data); //추가
 
		 client.connect();
		 client.send(data);
		 client.disconnect();
	 }
}
```

```java
package exception.ex1;

import java.util.Scanner;

public class MainV1 {
	 
	 public static void main(String[] args) {
		 
		 NetworkServiceV1_1 networkService = new NetworkServiceV1_1();
 
		 Scanner scanner = new Scanner(System.in);
		 
		 while (true) {
			 System.out.print("전송할 문자: ");
			 String input = scanner.nextLine();
			 if (input.equals("exit")) {
				 break;
			 }
			networkService.sendMessage(input);
			System.out.println();
		 }
		 System.out.println("프로그램을 정상 종료합니다.");
	 }
}
```

### 정상 흐름과 예외 흐름

반환 값을 쓰는 순간, 이미 정상 흐름과 예외 흐름이 섞여버리게 된다.

어떻게 하면 정상 흐름과 예외 흐름을 분리할 수 있을까?

- 이 문제를 해결하기 위해 바로 예외 처리 메커니즘이 존재한다
- 예외 처리를 사용하면 정상 흐름과 예외 흐름을 명확하게 분리할 수 있다!

예외처리

1. 예외는 잡아서 처리하거나 밖으로 던져야 한다.
2. 예외를 잡거나 던질 때 지정한 예외뿐만 아니라 그 예외의 자식들도 함께 처리할 수 있다.
    1. 예를 들어서 Exception을 catch로 잡으면 그 하위 예외들도 모두 잡을 수 있다.
    2. 예를 들어서 Exception을 throws로 던지면 그 하위 예외들도 모두 던질 수 있다.

- 예외를 처리하지 못하고 계속 던지면
    
    자바 main() 밖으로 예외를 던지면 예외 로그를 출력하면서 시스템이 종료된다.
